
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Lab Informatika
 */
public class DataMovie extends javax.swing.JFrame {

    Connection koneksi;
    Statement stat;
    ResultSet rs;
    Konektor conn;
    PreparedStatement pst;

    private final DefaultTableModel model;

    /**
     * Creates new form DataMovie
     */
    public DataMovie() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        model = new DefaultTableModel();

        jTable1.setModel(model);

        model.addColumn("Judul");
        model.addColumn("Alur");
        model.addColumn("Penokohan");
        model.addColumn("Akting");
        model.addColumn("Nilai");

        loadData();
    }

    public void loadData() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        try {
            String sql = "SELECT * FROM movie";
            conn = new Konektor();
            koneksi = conn.getKoneksi();
            stat = koneksi.createStatement();
            rs = stat.executeQuery(sql);

            while (rs.next()) {
                Object[] o = new Object[5];
                o[0] = rs.getString("judul");
                o[1] = rs.getString("alur");
                o[2] = rs.getString("penokohan");
                o[3] = rs.getString("akting");
                o[4] = rs.getString("nilai");

                model.addRow(o);
            }
            rs.close();
            stat.close();
        } catch (Exception e) {
            System.out.println("Terjadi kesalahan load data");
        }
    }
    
    public void clear() {
        txJudul.setText("");
        txAlur.setText("");
        txPenokohan.setText("");
        txAkting.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txJudul = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txAlur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txPenokohan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txAkting = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Judul");

        txJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txJudulActionPerformed(evt);
            }
        });

        jLabel2.setText("Alur");

        jLabel3.setText("Penokohan");

        jLabel4.setText("Akting");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("PROGRAM PENILAIAN FILM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txJudul)
                            .addComponent(txAlur)
                            .addComponent(txPenokohan)
                            .addComponent(txAkting)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(btnTambah)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(137, 137, 137))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(137, 137, 137)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txAlur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txPenokohan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txAkting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah)
                            .addComponent(btnDelete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(btnClear)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txJudulActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String judul = txJudul.getText();
        String alur = txAlur.getText();
        String penokohan = txPenokohan.getText();
        String akting = txAkting.getText();

        double nilai = 0;
        double nalur, ntokoh, nakting;
        nalur = Double.valueOf(alur);
        ntokoh = Double.valueOf(penokohan);
        nakting = Double.valueOf(akting);
        nilai = (nalur + ntokoh + nakting) / 3;

        try {
            String sql = "INSERT INTO movie VALUES(?,?,?,?,?)";
            conn = new Konektor();
            koneksi = conn.getKoneksi();
            pst = koneksi.prepareStatement(sql);

            pst.setString(1, judul);
            pst.setString(2, alur);
            pst.setString(3, penokohan);
            pst.setString(4, akting);
            pst.setDouble(5, nilai);
            pst.executeUpdate();
            pst.close();
        } catch (Exception e) {
            System.out.println(e);
        }
        loadData();
        clear();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        if (i == -1) {
            return;
        }
        String judul = txJudul.getText();
        String alur = txAlur.getText();
        String penokohan = txPenokohan.getText();
        String akting = txAkting.getText();

        double nilai = 0;
        double nalur, ntokoh, nakting;
        nalur = Double.valueOf(alur);
        ntokoh = Double.valueOf(penokohan);
        nakting = Double.valueOf(akting);
        nilai = (nalur + ntokoh + nakting) / 3;

        try {
            String sql = "UPDATE movie set alur=?, penokohan=?, akting=?, nilai=? WHERE judul=?";
            conn = new Konektor();
            koneksi = conn.getKoneksi();
            pst = koneksi.prepareStatement(sql);

            pst.setString(1, alur);
            pst.setString(2, penokohan);
            pst.setString(3, akting);
            pst.setDouble(4, nilai);
            pst.setString(5, judul);

            pst.executeUpdate();
            pst.close();
            JOptionPane.showMessageDialog(null, "Data berhasil dirubah");
        } catch (Exception e) {
            System.out.println("Update error");
            System.out.println(e);
        } finally {
            loadData();
            clear();
            txJudul.setEnabled(true);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        if (i == -1) {
            return;
        }

        String judul = (String) model.getValueAt(i, 0);
        String alur = (String) model.getValueAt(i, 1);
        String penokohan = (String) model.getValueAt(i, 2);
        String akting = (String) model.getValueAt(i, 3);
        String nilai = (String) model.getValueAt(i, 4);

        txJudul.setText(judul);
        txAlur.setText(alur);
        txPenokohan.setText(penokohan);
        txAkting.setText(akting);
        txJudul.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        if (i == -1) {
            return;
        }

        String judul = (String) model.getValueAt(i, 0);

        int pernyataan = JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (pernyataan == JOptionPane.OK_OPTION) {
            try {
                String sql = "DELETE FROM movie where judul=?";
                conn = new Konektor();
                koneksi = conn.getKoneksi();
                pst = koneksi.prepareStatement(sql);
                pst.setString(1, judul);
                pst.executeUpdate();
                pst.close();
                JOptionPane.showMessageDialog(null, "Data terhapus");
            } catch (Exception e) {
                System.out.println("Delete Error");
                System.out.println(e);
            } finally {
                loadData();
                clear();
                txJudul.setEnabled(true);
            }
        }
        else if (pernyataan == JOptionPane.CANCEL_OPTION) {
            
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
        txJudul.setEnabled(true);
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txAkting;
    private javax.swing.JTextField txAlur;
    private javax.swing.JTextField txJudul;
    private javax.swing.JTextField txPenokohan;
    // End of variables declaration//GEN-END:variables
}
